### ISSUE TITLE
Running same Pdf URL for batched and single 

### ISSUE THREAD

**Issue by GWL-QA** [BrowserStackCE/percy-pdf#1]
Hi Team, Please check while the URL's in example.single and example.batched are different. I'm running the command for batched and for single still it was running the same pdf URL which is in example.batched

**Comment by shaikhalid** [comment]
Hi thanks for creating the issue, this was due the incorrect config in the wdio conf file. This has been fixed in the new 'scope' branch. We have removed the 2 files for batched and single now we only have one file for both. 

Also the new scope branch will allow you to capture pdfs in a format that can potentially be compared to websites.

**Comment by shaikhalid** [comment]
There are quite few improvements in the new repo please go over the read me again
